/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.principal;

import controlador.Coordinador;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.vo.EstadoVO;
import modelo.vo.MaterialVO;
import modelo.vo.PacienteVO;

/**
 *
 * @author victo
 */
public class VentanaGestionInventario extends javax.swing.JFrame {

    private Coordinador miCoordinador;
    private DefaultTableModel modelo;
    /**
     * Creates new form VentanaGestionInventario
     */
    public VentanaGestionInventario() {
        initComponents();
        cargarTabla();
        limpiar();
    }
    
    public void setCoordinador(Coordinador miCoordinador) {
           this.miCoordinador=miCoordinador;
           
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        fondoInventario = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIÓN DE INVENTARIO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titulo.setText("MENU - GESTIÓN DE INVENTARIO");

        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        btnAgregar.setText("+");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("-");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnRegresar))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titulo)
                .addGap(24, 24, 24)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 330));

        fondoInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInventario.png"))); // NOI18N
        getContentPane().add(fondoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.miCoordinador.mostrarVentanaMenuPrincipal();
        limpiar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        if ((evt.getKeyChar()<65 || evt.getKeyChar()>90) && (evt.getKeyChar()<48 || evt.getKeyChar()>57)){
            evt.consume();
        }
        if(txtPlaca.getText().length() >= 7){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        llenarTabla(txtPlaca.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       int fila, columna;
        fila=tablaDatos.getSelectedRow();
        columna=tablaDatos.getSelectedColumn();
        if((fila>0) || (columna>0))     
            modificarColumnaMayor(columna,fila,1);
        else
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN MATERIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int fila, columna;
        fila=tablaDatos.getSelectedRow();
        columna=tablaDatos.getSelectedColumn();
        if((fila>0) || (columna>0))     
            modificarColumnaMayor(columna,fila,-1);
        else
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN PACIENTE", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
    habilitarBoton();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaKeyReleased
    public void habilitarBoton()
       {
            if (!txtPlaca.getText().isEmpty())
            {
                btnBuscar.setEnabled(true);
            }
            else
            {
                btnBuscar.setEnabled(false);
                btnQuitar.setEnabled(false);
                btnAgregar.setEnabled(false);
            }
        }
    public void cargarTabla(){
        String datos[][]={};
        String columna[]={"ID","Material","Cantidad"};
        modelo=new DefaultTableModel(datos,columna){
            public boolean isCellEditable(int rowIndex, int columnIndex){return false;}
        };
        tablaDatos.setModel(modelo);
    }
    
    
    public static int objectToInt(Object obj){
        int x = Integer.parseInt(obj.toString());
        return x;
    }
    
     public void modificarColumnaMayor(int columna, int fila, int valor){
        MaterialVO material=new MaterialVO();
        material=miCoordinador.buscarMaterial(objectToInt(modelo.getValueAt(fila, 0)),txtPlaca.getText());
        
        material.setCantidad(material.getCantidad()+valor);
        
        String resp=miCoordinador.modificarMaterial(material);
					
	if(resp.equals("ok")){
             llenarTabla(txtPlaca.getText());
            JOptionPane.showMessageDialog(null, "CANTIDAD MODIFICADA EXISOTAMENTE");
           
	}else{
            //System.out.println(resp);
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
	}
    }
     
      public void llenarTabla(String placa){
        ArrayList<MaterialVO> listaMateriales=miCoordinador.getListaMateriales(placa);
        if(listaMateriales.size()<1)
            JOptionPane.showMessageDialog(null, "PLACA INVALIDA", "ERROR", JOptionPane.ERROR_MESSAGE);
        modelo.setRowCount(0);
        int contador=0;
        for(MaterialVO m:listaMateriales){
            modelo.insertRow(contador, new Object[]{});
            modelo.setValueAt(m.getId(), contador, 0);
            modelo.setValueAt(m.getNombre(), contador, 1);
            modelo.setValueAt(m.getCantidad(), contador, 2);
            btnAgregar.setEnabled(true);
            btnQuitar.setEnabled(true);
        }
    }
      
    public void limpiar(){
        txtPlaca.setText("");
        btnBuscar.setEnabled(false);
        btnQuitar.setEnabled(false);
        btnAgregar.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel fondoInventario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaDatos;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
