/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.reporte;



import controlador.Coordinador;

import controlador.Coordinador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.vo.AmbulanciaVO;
import modelo.vo.FechaVO;
import modelo.vo.MunicipioVO;
import modelo.vo.PacienteVO;
import modelo.vo.ReporteVO;

/**
 *
 * @author jose-
 */
public class VentanaRegistrarEmergencia extends javax.swing.JFrame {
    
    private Coordinador miCoordinador;

    /**
     * Creates new form VentanaRegistrarEmergencia
     */
    public VentanaRegistrarEmergencia() {
        initComponents();
    }
    
    public void setCoordinador(Coordinador miCoordinador) {
        this.miCoordinador=miCoordinador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cbMunicipio = new javax.swing.JComboBox<>();
        cbClinicas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFRdia = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        btnRegistrarReporte = new javax.swing.JButton();
        txtFRmes = new javax.swing.JTextField();
        txtFRan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("MENU - REGISTRAR REPORTE");

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel3.setText("BUSCAR ID DEL AFILIADO");

        jLabel4.setText("SELECCIONA MUNICIPIO");

        jLabel5.setText("SELECCIONA CLINICA");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        cbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new MunicipioVO[] { MunicipioVO.BARUTA, MunicipioVO.CHACAO, MunicipioVO.HATILLO, MunicipioVO.LIBERTADOR, MunicipioVO.SUCRE }));
        cbMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipioActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("INFORMACION DEL REPORTE");

        jLabel8.setText("FECHA DE LA EMERGENCIA");

        jLabel9.setText("PLACA DE LA AMBULANCIA");

        txtFRdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFRdiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFRdiaKeyTyped(evt);
            }
        });

        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
        });

        btnRegistrarReporte.setText("REGISTRAR REPORTE");
        btnRegistrarReporte.setEnabled(false);
        btnRegistrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarReporteActionPerformed(evt);
            }
        });

        txtFRmes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFRmesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFRmesKeyTyped(evt);
            }
        });

        txtFRan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFRanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFRanKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("dd");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("mm");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbClinicas, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtFRdia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFRmes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFRan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel10)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel11)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel12))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel7)))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarReporte)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbClinicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFRdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFRmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFRan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarReporte)
                    .addComponent(btnRegresar))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 440, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/fondoEmergencia.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.miCoordinador.mostrarVentanaGestionReporte();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    
    public String[] convertirArreglo(){
        String[] aux=new String[6];
        
        return aux;
    }
    
    
    private void cbMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipioActionPerformed
        String item = cbMunicipio.getSelectedItem().toString();
        ArrayList<String> aux=miCoordinador.devolverClinicas(item);
        cbClinicas.setModel(new javax.swing.DefaultComboBoxModel<>());
        for(String a:aux){
            cbClinicas.addItem(a);
        }
    }//GEN-LAST:event_cbMunicipioActionPerformed

    private void btnRegistrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarReporteActionPerformed
       PacienteVO pacienteReg=new PacienteVO();
       pacienteReg=miCoordinador.buscarPaciente2(Integer.parseInt(txtId.getText()));
       if(pacienteReg!=null){  
            if(pacienteReg.getEstado().name().equals("ACTIVO")){
                AmbulanciaVO ambulancia=new AmbulanciaVO();
                ambulancia=miCoordinador.buscarAmbulancia(txtPlaca.getText());
                if(ambulancia!=null){
                    ReporteVO reporte=new ReporteVO();
                
                    FechaVO fechaReg=new FechaVO();
                    fechaReg.setDia(Integer.parseInt(txtFRdia.getText()));
                    fechaReg.setMes(Integer.parseInt(txtFRmes.getText()));
                    fechaReg.setAn(Integer.parseInt(txtFRan.getText()));
                
                    reporte.setId(Integer.parseInt(txtId.getText()));
                    reporte.setFechaRegistro(fechaReg);
                    reporte.setClinica(cbClinicas.getSelectedItem().toString());
                    reporte.setMunicipio((MunicipioVO) cbMunicipio.getSelectedItem());
                    reporte.setDescripcion(txtDescripcion.getText());
                    reporte.setPlaca(txtPlaca.getText());
                    
                    String resp=miCoordinador.RegistrarReporte(reporte);
                    if(resp.equals("ok") && validarFechaRegistro()==true ){
                        JOptionPane.showMessageDialog(null, "REPORTE  AGREGADO EXISOTAMENTE");
                        miCoordinador.mostrarVentanaGestionReporte();
                    }else{
                        JOptionPane.showMessageDialog(null, "ERROR AGREGANDO EL REPORTE", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "ESTA AMBULANCIA NO EXISTE", "ERROR", JOptionPane.ERROR_MESSAGE);
                }   
            }else{
                JOptionPane.showMessageDialog(null, "ESTE PACIENTE ESTA INACTIVO", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
                
       }else{
           JOptionPane.showMessageDialog(null, "ESTE PACIENTE NO EXISTE", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnRegistrarReporteActionPerformed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
       habilitarBoton();
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtFRdiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFRdiaKeyReleased
      habilitarBoton();
    }//GEN-LAST:event_txtFRdiaKeyReleased

    private void txtFRmesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFRmesKeyReleased
      habilitarBoton();
    }//GEN-LAST:event_txtFRmesKeyReleased

    private void txtFRanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFRanKeyReleased
     habilitarBoton();
    }//GEN-LAST:event_txtFRanKeyReleased

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
    habilitarBoton();
    }//GEN-LAST:event_txtPlacaKeyReleased

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
    habilitarBoton();
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57){
            evt.consume();
        }     // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtFRdiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFRdiaKeyTyped
        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtFRdiaKeyTyped

    private void txtFRmesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFRmesKeyTyped
        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtFRmesKeyTyped

    private void txtFRanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFRanKeyTyped
        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtFRanKeyTyped
       
    public boolean validarFechaRegistro(){
        int diaFR, mesFR, yearFR;
        
        
        diaFR = Integer.parseInt(txtFRdia.getText());
        mesFR = Integer.parseInt(txtFRmes.getText());
        yearFR = Integer.parseInt(txtFRan.getText());
        
        if(yearFR == 2022){
            if(mesFR == 1){
               if((diaFR > 0 && diaFR < 32)){
                   return true;
               } else{
                   return false;
               }
            }
            else if(mesFR == 2){
                if(diaFR> 0 && diaFR < 30){
                   return true;
               } else{
                   return false;
               }
            }
            else if(mesFR == 3){
               if((diaFR > 0 && diaFR < 32)){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 4){
               if(diaFR > 0 && diaFR < 31){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 5){
               if(diaFR > 0 && diaFR < 32){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 6){
               if(diaFR> 0 && diaFR < 31){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 7){
               if(diaFR > 0 && diaFR < 32){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 8){
               if(diaFR > 0 && diaFR < 32){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 9){
               if(diaFR> 0 && diaFR < 31){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 10){
               if(diaFR > 0 && diaFR < 32){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 11){
               if(diaFR > 0 && diaFR < 31){
                   return true;
               } else{
                   return false;
               } 
            }
            else if(mesFR == 12){
               if(diaFR > 0 && diaFR< 32){
                   return true;
               } else{
                   return false;
               } 
            }
            else{
              return false;  
            }
            
        } 
        else{
           return false;
        }
        
    }
    public void habilitarBoton()
       {
            if (!txtId.getText().isEmpty() && !txtFRdia.getText().isEmpty() && !txtFRmes.getText().isEmpty()
                    && !txtFRan.getText().isEmpty() && !txtPlaca.getText().isEmpty() && !txtDescripcion.getText().isEmpty())
            {
                btnRegistrarReporte.setEnabled(true);
            }
            else
            {
            btnRegistrarReporte.setEnabled(false);
            }
        }
    public void limpiar()
    {
        txtId.setText("");
        txtFRdia.setText("");
        txtFRmes.setText("");
        txtFRan.setText("");
        cbMunicipio.setSelectedIndex(-1);
        btnRegistrarReporte.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarReporte;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbClinicas;
    public javax.swing.JComboBox<MunicipioVO> cbMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFRan;
    private javax.swing.JTextField txtFRdia;
    private javax.swing.JTextField txtFRmes;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
