/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.paciente;

import controlador.Coordinador;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.vo.EstadoVO;
import modelo.vo.FechaVO;
import modelo.vo.GeneroVO;
import modelo.vo.MunicipioVO;
import modelo.vo.PacienteVO;
import modelo.vo.TipoSangreVO;
import static vista.paciente.VentanaModificarPaciente.objectToInt;

/**
 *
 * @author jose-
 */
public class VentanaCambiarEstadoPaciente extends javax.swing.JFrame {

    private Coordinador miCoordinador;
    private DefaultTableModel modelo;
    /**
     * Creates new form VentanaDesactivarPaciente
     */
    public VentanaCambiarEstadoPaciente() {
        initComponents();
        cargarTabla();
    }

    public void setCoordinador(Coordinador miCoordinador) {
       this.miCoordinador=miCoordinador;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroAfiliacion = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstatusPaciente = new javax.swing.JTable();
        btnEstatus = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESTATUS DEL PACIENTE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeroAfiliacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroAfiliacionKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumeroAfiliacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 180, -1));

        titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titulo.setText("DESACTIVAR USUARIO");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        tablaEstatusPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID del Afiliado", "Nombres", "Apellidos", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaEstatusPaciente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 350, 210));

        btnEstatus.setText("ACTIVAR/DESACTIVAR USUARIO");
        btnEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatusActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 220, -1));

        btnBuscar.setText("BUSCAR POR ID");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoEstatusPaciente.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.miCoordinador.mostrarVentanaGestionPaciente();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        PacienteVO pacienteMod=new PacienteVO();
       try{
           pacienteMod=miCoordinador.buscarPaciente2(Integer.parseInt(txtNumeroAfiliacion.getText()));
           if(pacienteMod!=null){  
                llenarTabla(pacienteMod);
            }else{
                JOptionPane.showMessageDialog(null, "ESTE PACIENTE NO EXISTE", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
       }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null, "DEBE ESCRIBIR PRIMERO EL ID DEL PACIENTE", "ERROR", JOptionPane.ERROR_MESSAGE); 
       }
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNumeroAfiliacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroAfiliacionKeyTyped
       if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57){
        evt.consume();
        }
        if(txtNumeroAfiliacion.getText().length() >= 8){
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(txtNumeroAfiliacion.getText().equals(""))
            llenarTabla();
    }//GEN-LAST:event_txtNumeroAfiliacionKeyTyped

    private void btnEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatusActionPerformed
        int fila, columna;
        fila=tablaEstatusPaciente.getSelectedRow();
        columna=tablaEstatusPaciente.getSelectedColumn();
        if((fila>0) || (columna>0))     
            modificarColumnaMayor(columna,fila);
        else
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN PACIENTE", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnEstatusActionPerformed

    public static int objectToInt(Object obj){
        int x = Integer.parseInt(obj.toString());
        return x;
    }
    
     public void modificarColumnaMayor(int columna, int fila){
        PacienteVO pacienteMod=new PacienteVO();
        pacienteMod=miCoordinador.buscarPaciente2(objectToInt(modelo.getValueAt(fila, 0)));
        
       //System.out.println(pacienteMod.getEstado().name());
        if(pacienteMod.getEstado()==EstadoVO.ACTIVO){
             //System.out.println(pacienteMod.getEstado().name());
           pacienteMod.setEstado(EstadoVO.INACTIVO);
          // System.out.println(pacienteMod.getEstado().name());
           
       }   
       else
           pacienteMod.setEstado(EstadoVO.ACTIVO);
        
        String resp=miCoordinador.modificarPaciente2(pacienteMod);
					
	if(resp.equals("ok")){
            if(txtNumeroAfiliacion.getText().equals(""))
                llenarTabla();
            else
                llenarTabla(pacienteMod);
            JOptionPane.showMessageDialog(null, "ESTADO MODIFICADO EXISOTAMENTE");
           
	}else{
            System.out.println(resp);
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
	}
    }
    
    
    public void cargarTabla(){
        String datos[][]={};
        String columna[]={"Numero Afiliacion","Nombre","Apellidos","Estado"};
        modelo=new DefaultTableModel(datos,columna){
            public boolean isCellEditable(int rowIndex, int columnIndex){return false;}
        };
        tablaEstatusPaciente.setModel(modelo);
    }
    
    public void llenarTabla(){
        ArrayList<PacienteVO> listaPacientes=miCoordinador.getListaPacientes2();
        modelo.setRowCount(0);
        int contador=0;
        for(PacienteVO p:listaPacientes){
            modelo.insertRow(contador, new Object[]{});
            modelo.setValueAt(p.getId(), contador, 0);
            modelo.setValueAt(p.getNombre(), contador, 1);
            modelo.setValueAt(p.getApellido(), contador, 2);
            modelo.setValueAt(p.getEstado().name(), contador, 3);
        }
    }
    
    public void llenarTabla(PacienteVO p){
        modelo.setRowCount(0);
        int contador=0;
        
        modelo.insertRow(contador, new Object[]{});
        modelo.setValueAt(p.getId(), contador, 0);
        modelo.setValueAt(p.getNombre(), contador, 1);
        modelo.setValueAt(p.getApellido(), contador, 2);
        modelo.setValueAt(p.getEstado().name(), contador, 3);
        
    }
    
    
    public void limpiar(){
        txtNumeroAfiliacion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEstatus;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaEstatusPaciente;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtNumeroAfiliacion;
    // End of variables declaration//GEN-END:variables

    
}
